### ISSUE TITLE
Stream TLS Bugfix reverted - need wrapSecure

### ISSUE THREAD

**Issue by slowbro** [reactphp/socket-client#24] opened 2015-02-03 17:15 UTC
In regards to this thread on reactphp/stream: https://github.com/reactphp/stream/issues/17

It was found that the Stream TLS Bugfix was reverted (https://bugs.php.net/bug.php?id=65137), making TLS Streams block again.

Per @cboden the wrapSecure version check will need to be removed. Just moving this issue over to the correct project :)

**Comment by cboden** [comment] 2015-02-03 23:26
@slowbro Some work has been done and some PRs are now in the capable hands of @clue.

Excellent troubleshooting and detail left in the previous issue! Just FYI on some of your comments and what's going on:

> The only way I know to reproduce this involves a lot of steps and a specific product

Yup! When we first found this bug it wasn't (still isn't) easily reproducible. I think I remember having to stand on one leg while doing a rain dance to replicate it. 

---

The issue is some C code in the PHP SSL module when asked how much data is remaining in its buffer will say 0 even though there's data left in it. This means to fully receive your message you'd have to send another one to jam it through, then that one becomes jammed. 

The "fix" we're doing in SocketClient is a necessary evil of sorts...stream_get_contents is like running a while loop asking for data from the buffer until it's truly empty. This *could* cause blocking if a client is malicious and not letting other connections access the event loop. However, in the case of a SocketClient that's not likely and is a risk worth taking as opposed to the entire lib not working properly.

**Comment by slowbro** [comment] 2015-02-03 23:30
Thanks @cboden!

**Comment by cboden** [comment] 2015-03-20 15:01
Merged. v0.4.3 being tagged shortly.

**Closed by cboden** 2015-03-20 15:01 UTC
Labels: bug
